version: '2'
services:
  kafka:
    image: spotify/kafka
    ports:
      - "9092:9092"
      - "2181:2181"
    environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  producer:
    image: akka-producer:0.1-SNAPSHOT
    depends_on:
      - kafka
  consumer:
    image: akka-consumer:0.1-SNAPSHOT
    depends_on:
      - kafka
