version: '2'
services:
  kafka:
    image: spotify/kafka
    ports:
      - "9092:9092"
      - "2181:2181"
    environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  producer:
    image: com.david/akka-producer:0.1-SNAPSHOT
    depends_on:
      - kafka
  akka-consumer:
    image: com.david/akka-consumer:0.1-SNAPSHOT
    depends_on:
      - kafka
  spark-master:
    image: bde2020/spark-master:2.3.0-hadoop2.7
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - "ENABLE_INIT_DAEMON=false"
  spark-worker-1:
    image: bde2020/spark-worker:2.3.0-hadoop2.7
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "ENABLE_INIT_DAEMON=false"
  spark-worker-2:
    image: bde2020/spark-worker:2.3.0-hadoop2.7
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8084:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "ENABLE_INIT_DAEMON=false"
  spark-consumer:
    image: com.david/spark-consumer:0.1-SNAPSHOT
    depends_on:
      - spark-master
      - spark-worker-1
      - spark-worker-2
    environment:
      - "ENABLE_INIT_DAEMON=false"