apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper
  name: zookeeper-svc
spec:
  type: NodePort
  ports:
  - name: zookeeper-port
    port: 2181
    nodePort: 30181
    targetPort: 2181
  - name: zookeeper-follower
    protocol: TCP
    port: 2888
    targetPort: 2888
  - name: zookeeper-leader
    protocol: TCP
    port: 3888
    targetPort: 3888
  selector:
    app: zookeeper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zookeeper
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      hostname: zookeeper
      containers:
      - image: wurstmeister/zookeeper
        imagePullPolicy: IfNotPresent
        name: zookeeper
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888