apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
  labels:
    app: spark-worker
spec:
  replicas: 5
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      containers:
      - name: spark-master
        image: bde2020/spark-worker:2.3.0-hadoop2.7
        imagePullPolicy: IfNotPresent
        ports:
          - name: worker-port
            protocol: TCP
            containerPort: 8081
        env:
          - name: SPARK_MASTER
            value: "spark://{{SPARK_MASTER_HOST}}:{{SPARK_MASTER_PORT}}"
          - name: ENABLE_INIT_DAEMON
            value: "false"
